# 대상 서버 인벤토리 - Tailscale IP (Control Node: 100.110.158.124)

[rocky]

[ubuntu]
autoever-2	ansible_host=100.87.166.127
autoever-4	ansible_host=100.66.214.3

# 전체 타겟 그룹
[targets:children]
rocky
ubuntu

# 타겟 접속 공통 변수
[targets:vars]
ansible_user=user
